version: "3"
services:
  blockchain:
    image: krboktv/leveldb
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
    - "8080:8080"
    networks:
    - webnet
networks:
  webnet:


